---
- name: Clean up the existing Linux config
  hosts: localhost
  gather_facts: true
  collections:
  - purestorage.flasharray
  vars_files:
  - testdrive_vars.yaml
  tasks:

        - name: Get array info
          purefa_info:
            gather_subset:
            - network
            - volumes
            fa_url: "{{ fa1_ip }}"
            api_token: "{{ fa1_token }}"
          register: fa1_info

        - name: Rename volume linux-lun-01 to boot vol!
          purefa_volume:
            name: linux-lun-01
            rename: linux-boot-vol
            fa_url: "{{ fa1_ip }}"
            api_token: "{{ fa1_token }}"
...
