---
- name: Clean up the existing Linux config
  hosts: localhost
  gather_facts: true
  collections:
  - purestorage.flasharray
  vars_files:
  - ../resources/testdrive_vars.yaml
  tasks:

        - name: Get array info
          purefa_info:
            gather_subset:
            - network
            - volumes
            fa_url: "{{ fa1_ip }}"
            api_token: "{{ fa1_token }}"
          register: fa1_info

        - name: Rename volume LinuxVol1 to linux1-00
          purefa_volume:
            name: LinuxVol1
            rename: linux1-00
            fa_url: "{{ fa1_ip }}"
            api_token: "{{ fa1_token }}"
...
