- name: Create an ActiveCluster environment
  hosts: localhost
  gather_facts: true
  collections:
  - purestorage.flasharray
  vars_files:
    - testdrive_vars.yaml
  tasks:

  - name: Get source FlashArray info
    purefa_info:
      gather_subset:
      - minimum
      - network
      - interfaces
      fa_url: "{{ fa1_ip }}"
      api_token: "{{ fa1_token }}"
    register: fa1_info

  - name: Get destination FlashArray info
    purefa_info:
      gather_subset:
      - minimum
      - network
      - interfaces
      fa_url: "{{ fa2_ip }}"
      api_token: "{{ fa2_token }}"
    register: fa2_info

  - name: Connect arrays in ActiveCluster configuration
    purefa_connect:
      target_url: "{{ fa2_ip }}"
      target_api: "{{ fa2_token }}"
      connection: sync
      fa_url: "{{ fa1_ip }}"
      api_token: "{{ fa1_token }}"

  - name: Create demo pod
    purefa_pod:
      name: "{{ demo_pod }}"
      fa_url: "{{ fa1_ip }}"
      api_token: "{{ fa1_token }}"

  - name: Move demo volume to demo pod
    purefa_volume:
      name: "{{ demo_vol }}"
      move: "{{ demo_pod }}"
      fa_url: "{{ fa1_ip }}"
      api_token: "{{ fa1_token }}"

  - name: Stretch demo pod to destination array
    purefa_pod:
      name: "{{ demo_pod }}"
      stretch: "{{ fa2_info['purefa_info']['default']['array_name'] }}"
      fa_url: "{{ fa1_ip }}"
      api_token: "{{ fa1_token }}"

  - name: Wait for pod sync
    purefa_info:
      gather_subset: pods
      fa_url: "{{ fa1_ip }}"
      api_token: "{{ fa1_token }}"
    register: output
    retries: 40
    delay: 5
    until: "output | json_query('purefa_info.pods.\"{{ demo_pod }}\".arrays[].status') == ['online', 'online']"

  - name: Create host object on destination array
    purefa_host:
      host: "{{ ansible_hostname }}"
      iqn: "{{ ansible_iscsi_iqn }}"
      volume: "{{ demo_pod }}::{{ demo_vol }}"
      fa_url: "{{ fa2_ip }}"
      api_token: "{{ fa2_token }}"

  - name: Discover destination FlashArray using iSCSI
    open_iscsi:
      show_nodes: yes
      discover: yes
      portal: "{{ fa2_info.purefa_info.network[fa2_iscsi_port].address }}"
    register: fa2_iscsi_iqn

  - name: Connect to destination FlashArray over iSCSI
    open_iscsi:
      target: "{{ fa2_iscsi_iqn.nodes[0] }}"
      login: yes

  - name: Ensure new multipath links from destination array are connected
    command: /usr/sbin/multipath -r
